### ISSUE TITLE
Quote the source of your example

### ISSUE THREAD

**Issue by gbraad** [EvanHahn/English-text-highlighting#2]
Your example does not provide the source or title.

Either put: "A Scandal in Bohemia" by Arthur Conan Doyle at the top or bottom.

**Comment by EvanHahn** [comment]
Good idea. I believe this work is in the public domain, so I'm not breaking any laws, but I should attribute it.

**Comment by gbraad** [comment]
A link to wikisource or gothenburg would be possible, but I believe a simple attribution is enough, so I added this in #4

**Comment by EvanHahn** [comment]
Thanks! Did this.
